language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules


script: npm run build



deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  repo: Aquariuslt/aquariuslt.github.io
  target_branch: master
  on:
    branch: VUE
