language: node_js
node_js:
  - "6"
  - "7"

cache: yarn

install:
  - yarn


before_script:
  - yarn add global gulp

script: yarn run build

cache: yarn


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  repo: Aquariuslt/aquariuslt.github.io.git
  target_branch: master
  on:
    branch: VUE
