## Site
title: 'Aquariuslt Blog'
description: 'TL; DR'
author: 'Aquariuslt'
avator: 'https://img.aquariuslt.com/social/avator.png'
theme: '#448aff'
copyright: '2018 Aquariuslt'

## Nav Menus Configuration
nav:
  categories:
    enable: true
    prefix: '/category/:value'
  tags:
    enable: true
    prefix: '/tags'
  about:
    enable: true
    prefix: '/about'

## Friend Links
links:
  wxsm:
    name: 'Kary Blog'
    url: 'https://wxsm.space'
    desc: 'Kary Gor Blog'
  lousama:
    name: 'Lousama Blog'
    url: 'http://lousama.com'
    desc: '九鼎五百万年终Java大内高手,C字楼Picado刚枪选手'
  notfound:
    name: 'NotFound404'
    url: 'https://github.com/404NoFound'
    desc: '车底良哥'
  koala:
    name: '考拉的生活碎片'
    url: 'http://ikoala.net/'
    desc: '蛤交女大律师, 未毕业进驻上海TOP5律所'
  supremebb:
    name: '新片场 13c'
    url: 'http://corydon.cc/'
    desc: '新片场未来的Android职业队长,不带耳机打cs,脑放听声辩位把把吃鸡'
  xpp:
    name: 'CN RPMan'
    url: 'http://chjydu.com/'
    desc: 'ACM前区域金牌,世界未来的希望,口头禅是我来自黑马,请将我定义为智障'
  maview:
    name: 'Frank Xu'
    url: 'http://frankxfz.me'
    desc: 'NLP guy'
  arhi:
    name: 'Ahri'
    url: 'http://xuyuanxin.win'
    desc: '先有桃子后有天, 阿狸出门跑飞天'
  yulai:
    name: 'YuLai'
    url: 'https://yulaiz.com/'
    desc: '深圳地王 关内几套关外几栋'
  lz5z:
    name: 'Leo Blog'
    url: 'https://lz5z.com/'
    desc: 'KingSoft worker'
  songyuqiang:
    name: '西二旗'
    url: 'http://www.songyuqiang.com/'
    desc: '强神'

## Advance Features
features:
  disqus:
    enable: true
    short_name: aquariuslt
  manifest:
    enable: true
    name: 'Aquariuslt Blog'
    short_name: 'Blog'
    description: 'Aquariuslt Blog'
    theme_color: '#448aff'
    developer:
      name: 'Aquariuslt'
      url: 'https://github.com/aquariuslt'
  ## google analytics
  google_site_verification: s3PYm0fCo0ImPqqXoPLiUb_bFdlYODKw54VGSkcFgyE
  google_analytics: UA-68904127-1


## Others
cname: 'blog.aquariuslt.com'
