version: 1.0.0

site:
  host: blog.aquariuslt.com
  title: Aquariuslt Blog
  author: Aquariuslt
  avatar: https://avatars2.githubusercontent.com/u/6554061?s=460&v=4
  subtitle: TL; DR
  description: Personal Blog
  language: zh

build:
  directory:
    posts: posts
    public: dist
  favicon: src/favicon.ico
  theme: '@theme/v-material'
  colors:
    primary:
      light: '#ffffff'
      main: '#fafafa'
      dark: '#c7c7c7'
      contrastText: '#000000'

features:
  ga: s3PYm0fCo0ImPqqXoPLiUb_bFdlYODKw54VGSkcFgyE
  disqus: aquariuslt
  gallery: true
