version: 1.0.0

site:
  host: https://blog.aquariuslt.com
  title: Aquariuslt Blog
  subtitle: TL; DR
  description: Personal Blog
  language: zh

build:
  directory:
    posts: posts
    public: dist
  favicon: src/favicon.ico
  theme: '@theme/v-material'
  colors:
    primary:
      light: '#757ce8'
      main: '#3f50b5'
      dark: '#002884'
      contrastText: '#fff'
    secondary:
      light: '#ff7961'
      main: '#f44336'
      dark: '#ba000d'
      contrastText: '#000'


features:
  ga: s3PYm0fCo0ImPqqXoPLiUb_bFdlYODKw54VGSkcFgyE
  disqus: aquariuslt
