version: 1.0.0

site:
  host: https://blog.aquariuslt.com
  title: Aquariuslt Blog
  subtitle: TL; DR
  description: Personal Blog
  language: zh

build:
  directory:
    posts: posts
    public: dist
  favicon: src/favicon.ico
  theme: '@theme/v-material'

features:
  ga: s3PYm0fCo0ImPqqXoPLiUb_bFdlYODKw54VGSkcFgyE
  disqus: aquariuslt
