version: 2

jobs:
  ci:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/blog
    steps:
      - checkout:
          name: SCM
      - run:
          name: Install Dependencies
          command:
            - yarn
            - lerna bootstrap
      - run:
          name: Testing
          command: lerna run test
