version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node-browsers:10.16.0
    working_directory: ~/blog
    steps:
      - checkout:
          name: SCM
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Unit Test & Build
          command: yarn ci
      - run:
          name: Coverage Report
          command: "bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
