version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - ci
      - deploy:
          requires:
            - ci
          filters:
            branches:
              only: master

jobs:
  ci:
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/blog
    steps:
      - checkout
      - run: yarn
      - run: yarn bootstrap
      - run: yarn test
      - run: yarn build:prod
      - persist_to_workspace:
          root: ~/blog
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/blog
    steps:
      - checkout
      - attach_workspace:
          at: ~/blog
      - run:
          name: install gh-pages & lerna
          command: |
            sudo npm install -g --silent gh-pages
            git config user.email deploy-bot@circleci.com
            git config user.name "circleci"
      - run: sudo gh-pages --dist dist --repo https://${GITHUB_TOKEN}@github.com/aquariuslt/aquariuslt.github.io.git --branch master --add
      - run: yarn
      - run: yarn release
