version: 2

workflows:
  version: 2
  build:
    jobs:
      - ci

jobs:
  ci:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/blog
    steps:
      - checkout:
          name: SCM
      - run:
          name: Install Dependencies
          command:
            - yarn
            - lerna bootstrap
