version: 2
jobs:
  build:
    docker:
      -
        image: circleci/node:10.13.0
    working_directory: ~/blog
    steps:
      -
        checkout:
          name: SCM
      -
        run:
          name: Install Dependencies
          command: yarn install
      -
        run:
          name: Unit Test
          command: yarn test
      - run:
          name: Build
          command: yarn build

