version: 2.1

orbs:
  codecov: codecov/codecov@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/blog
    steps:
      - checkout:
          name: SCM
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Unit Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - codecov/upload:
          name: Coverage Report
          file: ~/blog/test/unit/coverage/lcov.info
