version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/blog
    steps:
      - checkout:
          name: SCM
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Unit Test & Build
          command: yarn ci
      - run:
          name: Coverage Report
          command: "bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN"
      - store_test_results:
          environment:
            JEST_JUNIT_OUTPUT: "test/unit/coverage/js-test-results.xml"
          path: test/unit/coverage/js-test-results.xml
