version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/blog
    steps:
      - checkout:
          name: SCM
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Unit Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - run:
          name: Coverage Report
          command: "bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN"
