version: 2

workflows:
  version: 2
  build:
    jobs:
      - ci

jobs:
  ci:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/blog
    steps:
      - checkout
      - run: yarn
      - run: yarn run bootstrap
      - run: yarn run test
