name: release

on:
  workflow_run:
    workflows: ['deploy']
    branches:
      - master
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: SCM
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Semantic-Release
        run: |
          yarn
          yarn release
